image: parrotstream/ubuntu-java:latest
pages:
  stage: deploy
  script:
  - apt install maven
  - apt install openssh-client
  - apt install sshpass
  - mvn clean install
  - sshpass -p "carol1234" scp -r ebook-0.0.1-SNAPSHOT.jar beniaminp@vps658548.ovh.net:/home/beniaminp/sublime/
  artifacts:
    paths:
    - public/
  only:
  - dev